/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package sis_exchange;

import Controlador.CRUD_Moneda;
import Entidades.Moneda;
import Utilidades.CellRenderer;
import Utilidades.HeaderCellRenderer;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.JTableHeader;

/**
 *
 * @author EDWARD
 */
public class FormViewMonedas extends javax.swing.JInternalFrame {

    public static DefaultTableModel dtm = null;
    /**
     * Creates new form FICursos
     */
    public FormViewMonedas() {
        initComponents();
        dtm = (DefaultTableModel) tblMonedas.getModel();
        getModeloTabla();
        try {
            VerDatos();
        } catch (Exception e) {
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        tblMonedas = new javax.swing.JTable();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        setTitle("TIPOS DE CAMBIO");
        setToolTipText("");
        setPreferredSize(new java.awt.Dimension(777, 284));
        addInternalFrameListener(new javax.swing.event.InternalFrameListener() {
            public void internalFrameOpened(javax.swing.event.InternalFrameEvent evt) {
                formInternalFrameOpened(evt);
            }
            public void internalFrameClosing(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosed(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameIconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeiconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameActivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeactivated(javax.swing.event.InternalFrameEvent evt) {
            }
        });

        tblMonedas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "*", "MONEDA", "COMPRA", "VENTA", "OFICIAL"
            }
        ));
        tblMonedas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblMonedasMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tblMonedas);

        getContentPane().add(jScrollPane2, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formInternalFrameOpened(javax.swing.event.InternalFrameEvent evt) {//GEN-FIRST:event_formInternalFrameOpened

    }//GEN-LAST:event_formInternalFrameOpened

    private void tblMonedasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblMonedasMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_tblMonedasMouseClicked

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane2;
    private static javax.swing.JTable tblMonedas;
    // End of variables declaration//GEN-END:variables

    public static void VerDatos() throws ClassNotFoundException, SQLException {
        try {
            int nf = tblMonedas.getRowCount();
            for (int i = 0; i < nf; i++) {
                dtm.removeRow(0);
            }
            for (Moneda m : CRUD_Moneda.ListaPersonalizadaMoneda()) {
                dtm.addRow(m.DatostoArray2());
            }
        } catch (Exception e) {
            System.out.println("Erro causado: "+e);
        }
    }
    public void getModeloTabla(){
        tblMonedas.setModel(dtm);        
        //color de los bordes de las celdas
        tblMonedas.setGridColor(new java.awt.Color(214, 213, 208)); 
        //tamaño de columnas
        tblMonedas.getColumnModel().getColumn(0).setPreferredWidth(0);
        tblMonedas.getColumnModel().getColumn(1).setPreferredWidth(100);
        tblMonedas.getColumnModel().getColumn(2).setPreferredWidth(50);
        tblMonedas.getColumnModel().getColumn(3).setPreferredWidth(50);
        tblMonedas.getColumnModel().getColumn(4).setPreferredWidth(50);
        //altura de filas
        tblMonedas.setRowHeight(20);
        //se asigna el nuevo CellRenderer a cada columna segun su contenido
        tblMonedas.getColumnModel().getColumn( 0 ).setCellRenderer( new CellRenderer("icon") );
        tblMonedas.getColumnModel().getColumn( 1 ).setCellRenderer( new CellRenderer("text") );
        tblMonedas.getColumnModel().getColumn( 2 ).setCellRenderer( new CellRenderer("text center") );
        tblMonedas.getColumnModel().getColumn( 3 ).setCellRenderer( new CellRenderer("text center") );
        tblMonedas.getColumnModel().getColumn( 4 ).setCellRenderer( new CellRenderer("text center") );
        //Se asigna nuevo header a la tabla
        JTableHeader jtableHeader = tblMonedas.getTableHeader();
        jtableHeader.setDefaultRenderer(new HeaderCellRenderer());
        tblMonedas.setTableHeader(  jtableHeader );
        
    }
}
