/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package sis_exchange;

import Controlador.CRUD_Caja;
import Controlador.CRUD_Configuracion;
import Controlador.CRUD_DetalleCaja;
import Entidades.Caja;
import Entidades.Configuracion;
import java.sql.SQLException;

import javax.swing.table.DefaultTableModel;
import Utilidades.CellRenderer;
import Utilidades.HeaderCellRenderer;
import java.text.DecimalFormat;
import java.text.DecimalFormatSymbols;
import javax.swing.JOptionPane;
import javax.swing.table.JTableHeader;


/**
 *
 * @author EDWARD
 */
public final class FormInicioCaja extends javax.swing.JDialog {
    
    public static DefaultTableModel dtm = null;
    public static int idCaja = 0;
    public static double total = 0;
    


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    /**
     * Creates new form FICursos
     */
    public FormInicioCaja(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        dtm = (DefaultTableModel) tblDetalleCaja.getModel();
        getModeloTabla();
        try {
            CargarComboCaja();
            
            idCaja = FORM_PRINCIPAL.idcaja;
            cmbCaja.setSelectedItem(CRUD_Caja.getNombreCaja(idCaja));
            cargarDatos(idCaja);
            if (Ingreso.idusuario==1) {
                cmbCaja.setEnabled(true);
            } else {
                cmbCaja.setEnabled(false);
            }   
        } catch (Exception e) {
        }
    }
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        cmbCaja = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        datFechaInicio = new datechooser.beans.DateChooserCombo();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblDetalleCaja = new javax.swing.JTable();
        jLabel3 = new javax.swing.JLabel();
        txtTotal = new javax.swing.JTextField();
        btnCancelar = new javax.swing.JButton();
        btnAbrir = new javax.swing.JButton();

        setTitle("ABRIR CAJA");
        setLocationByPlatform(true);
        setModal(true);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Elija la caja a iniciar operaciones:"));

        jLabel1.setText("Caja:");

        cmbCaja.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cmbCaja.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cmbCajaItemStateChanged(evt);
            }
        });

        jLabel2.setText("Fecha de Apertura:");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(62, 62, 62)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel2)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(datFechaInicio, javax.swing.GroupLayout.PREFERRED_SIZE, 217, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cmbCaja, javax.swing.GroupLayout.PREFERRED_SIZE, 335, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(140, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(cmbCaja, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel2)
                    .addComponent(datFechaInicio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Saldos en caja por moneda extrangera"));

        tblDetalleCaja.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "MONEDA", "SALDO EN CAJA", "T/C", "SALDO EN Bs."
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.Double.class, java.lang.Double.class, java.lang.Double.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblDetalleCaja.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblDetalleCajaMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tblDetalleCaja);
        if (tblDetalleCaja.getColumnModel().getColumnCount() > 0) {
            tblDetalleCaja.getColumnModel().getColumn(0).setResizable(false);
            tblDetalleCaja.getColumnModel().getColumn(1).setResizable(false);
        }

        jLabel3.setFont(new java.awt.Font("DejaVu Sans", 1, 12)); // NOI18N
        jLabel3.setText("TOTAL BS. EN CAJA:");

        txtTotal.setBackground(new java.awt.Color(0, 0, 0));
        txtTotal.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        txtTotal.setForeground(new java.awt.Color(255, 255, 255));
        txtTotal.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txtTotal.setText("0.00");
        txtTotal.setEnabled(false);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 639, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 222, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtTotal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addContainerGap())
        );

        btnCancelar.setText("CANCELAR");
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });

        btnAbrir.setText("ABRIR");
        btnAbrir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAbrirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(504, 504, 504)
                        .addComponent(btnAbrir, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(11, 11, 11)
                        .addComponent(btnCancelar))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 274, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnAbrir, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnCancelar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
    private void formInternalFrameOpened(javax.swing.event.InternalFrameEvent evt) {//GEN-FIRST:event_formInternalFrameOpened
 
    }//GEN-LAST:event_formInternalFrameOpened

    private void tblDetalleCajaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblDetalleCajaMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_tblDetalleCajaMouseClicked

    private void btnAbrirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAbrirActionPerformed
        // TODO add your handling code here:
        boolean guardar=false;
        boolean estpa = false;
        try {
            java.util.Date date = new java.util.Date();
            java.sql.Timestamp fecha = new java.sql.Timestamp(date.getTime());
            
            Caja c = new Caja();
            c.setIdCaja(idCaja);
            c.setDescripcion(cmbCaja.getSelectedItem().toString());
            c.setSaldoInicial(total);
            c.setSaldoFinal(0);
            c.setFechaApertura(fecha);
            // indicamos el estado de la caja 1= abierto; 0 = cerrado
            c.setEstado(1);
            int resp = JOptionPane.showConfirmDialog(this, "¿Esta seguro de inciar la caja con los saldos indicados?", "Alerta!", JOptionPane.YES_NO_OPTION, JOptionPane.ERROR_MESSAGE);
            System.out.println("Eligio:"+resp);
            if (resp==0) {
                guardar = CRUD_Caja.Guardar(c);
                estpa = CRUD_DetalleCaja.pralmSaldo(idCaja, 1);
                System.out.println("Estado guardar:" + guardar);
                System.out.println("estado procedimiento:"+ estpa);
                if (guardar == true) {
                    System.out.println("Se inicio la caja.");
                    FORM_PRINCIPAL.iniciar(true,cmbCaja.getSelectedItem().toString(),fecha.toString());
                    FORM_PRINCIPAL.idcaja=idCaja;
                    // Se incia en nuevamente las operaciones
                    boolean est = CRUD_Configuracion.ActualizaNumeroOperacion(new Configuracion(0, 0, 0, 0, 0,"",1,1,idCaja, Ingreso.idusuario));
                    this.dispose();
                } else {
                    JOptionPane.showMessageDialog(this, "No se pudo inciar la caja verifique los datos o contactese con su administrador del sistema", "Error", JOptionPane.ERROR_MESSAGE);
                }
            }
        } catch (Exception e) {
        }
    }//GEN-LAST:event_btnAbrirActionPerformed

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_btnCancelarActionPerformed

    private void cmbCajaItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cmbCajaItemStateChanged
        // TODO add your handling code here:
        try {
                idCaja = CRUD_Caja.getidCaja(cmbCaja.getSelectedItem().toString());
                cargarDatos(idCaja);
        } catch (Exception e) {
            System.err.println("Error" + e);
        }
    }//GEN-LAST:event_cmbCajaItemStateChanged

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAbrir;
    private javax.swing.JButton btnCancelar;
    private javax.swing.JComboBox<String> cmbCaja;
    private datechooser.beans.DateChooserCombo datFechaInicio;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane2;
    public static javax.swing.JTable tblDetalleCaja;
    private javax.swing.JTextField txtTotal;
    // End of variables declaration//GEN-END:variables
    
    public void CargarComboCaja() throws ClassNotFoundException, SQLException {
        
        cmbCaja.removeAllItems();
        for (Caja c : CRUD_Caja.ListarporCaja()) {
            cmbCaja.addItem(c.getDescripcion());
        }
        
    }
    public static void VerDatos(int idcaja) throws ClassNotFoundException, SQLException {
        total=0;
        try {
            int nf = tblDetalleCaja.getRowCount();
            for (int i = 0; i < nf; i++) {
                dtm.removeRow(0);
            }
            for (Object [] lista : CRUD_DetalleCaja.VistaDetalleCaja(idcaja)) {
                dtm.addRow(lista);
                total+=Double.parseDouble(String.valueOf(lista[3]));
            }
        } catch (Exception e) {
            System.out.println(e.toString());
            //JOptionPane.showMessageDialog(rootPane, e.toString());
        }
    }
    public void getModeloTabla(){
        tblDetalleCaja.setModel(dtm);        
        //color de los bordes de las celdas
        tblDetalleCaja.setGridColor(new java.awt.Color(214, 213, 208)); 
        //tamaño de columnas
        /*Oculta la primera columna
        tblDetalleCaja.getColumnModel().getColumn(0).setMaxWidth(0);
        tblDetalleCaja.getColumnModel().getColumn(0).setMinWidth(0);
        tblDetalleCaja.getColumnModel().getColumn(0).setPreferredWidth(0);
        tblDetalleCaja.getColumnModel().getColumn(0).setResizable(false);
        //---*/
        tblDetalleCaja.getColumnModel().getColumn(0).setPreferredWidth(60);
        tblDetalleCaja.getColumnModel().getColumn(1).setPreferredWidth(30);
        tblDetalleCaja.getColumnModel().getColumn(2).setPreferredWidth(20);
        tblDetalleCaja.getColumnModel().getColumn(3).setPreferredWidth(30);
        //altura de filas
        tblDetalleCaja.setRowHeight(20);
        //se asigna el nuevo CellRenderer a cada columna segun su contenido
        tblDetalleCaja.getColumnModel().getColumn( 0 ).setCellRenderer( new CellRenderer("text") );
        tblDetalleCaja.getColumnModel().getColumn( 1 ).setCellRenderer( new CellRenderer("numero") );
        tblDetalleCaja.getColumnModel().getColumn( 2 ).setCellRenderer( new CellRenderer("numero") );
        tblDetalleCaja.getColumnModel().getColumn( 3 ).setCellRenderer( new CellRenderer("numero") );
        //Se asigna nuevo header a la tabla
        JTableHeader jtableHeader = tblDetalleCaja.getTableHeader();
        jtableHeader.setDefaultRenderer(new HeaderCellRenderer());
        tblDetalleCaja.setTableHeader(  jtableHeader );
        
    }

    private void cargarDatos(int id) throws ClassNotFoundException, SQLException {
        
            VerDatos(id);
            DecimalFormatSymbols simbolo=new DecimalFormatSymbols();
            simbolo.setDecimalSeparator('.');
            simbolo.setGroupingSeparator(',');
            DecimalFormat formatea = new DecimalFormat("###,###.##",simbolo);
            formatea.setMinimumFractionDigits(2);
            
            txtTotal.setText(formatea.format(total));
            
            btnAbrir.requestFocus();
    }
}
