/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package sis_exchange;

import Controlador.CRUD_Caja;
import Entidades.Caja;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import java.text.NumberFormat;
import java.util.Locale;
import javax.swing.text.DefaultFormatterFactory;
import javax.swing.text.NumberFormatter;

/**
 *
 * @author EDWARD
 */
public class FormGestionCaja extends javax.swing.JInternalFrame{

    /**
     * Creates new form FICursos
     */
    public FormGestionCaja() {
        initComponents();
    }
    public static boolean modif = false;
    DefaultTableModel dtm = null;
    public static int idCaja = 0;
    public static String desc = "";
    public ModeloTabla modeloTabla = new ModeloTabla();

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        pInicio = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblCaja = new javax.swing.JTable();
        jPanel3 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        txtIdCaja = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtNombre = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        txtSaldoBolivianos = new javax.swing.JFormattedTextField();
        jLabel7 = new javax.swing.JLabel();
        txtSaldoDolares = new javax.swing.JFormattedTextField();
        jLabel4 = new javax.swing.JLabel();
        dateFechaVApertura = new datechooser.beans.DateChooserCombo();
        jLabel8 = new javax.swing.JLabel();
        dateFechaCierre = new datechooser.beans.DateChooserCombo();
        rbtnEstado = new javax.swing.JRadioButton();
        jLabel1 = new javax.swing.JLabel();
        pInferior = new javax.swing.JPanel();
        btnDetalleCaja = new javax.swing.JButton();
        btnNuevo = new javax.swing.JButton();
        btnGuardar = new javax.swing.JButton();
        btnEliminar = new javax.swing.JButton();

        setClosable(true);
        setTitle("Gestion de Cajas");
        setToolTipText("");
        addInternalFrameListener(new javax.swing.event.InternalFrameListener() {
            public void internalFrameOpened(javax.swing.event.InternalFrameEvent evt) {
                formInternalFrameOpened(evt);
            }
            public void internalFrameClosing(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosed(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameIconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeiconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameActivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeactivated(javax.swing.event.InternalFrameEvent evt) {
            }
        });

        pInicio.setPreferredSize(new java.awt.Dimension(899, 150));
        pInicio.setLayout(new java.awt.BorderLayout());

        tblCaja.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "ID", "NOMBRE", "SALDO BOLIVIANOS", "SALDO DOLARES", "FECHA APERTURA", "FECHA CIERRE", "ESTADO"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Boolean.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblCaja.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblCajaMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tblCaja);
        if (tblCaja.getColumnModel().getColumnCount() > 0) {
            tblCaja.getColumnModel().getColumn(0).setResizable(false);
            tblCaja.getColumnModel().getColumn(1).setResizable(false);
            tblCaja.getColumnModel().getColumn(2).setResizable(false);
            tblCaja.getColumnModel().getColumn(3).setResizable(false);
            tblCaja.getColumnModel().getColumn(4).setResizable(false);
            tblCaja.getColumnModel().getColumn(6).setResizable(false);
        }

        pInicio.add(jScrollPane2, java.awt.BorderLayout.CENTER);

        getContentPane().add(pInicio, java.awt.BorderLayout.PAGE_START);

        jPanel3.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        java.awt.GridBagLayout jPanel3Layout = new java.awt.GridBagLayout();
        jPanel3Layout.columnWidths = new int[] {0, 20, 0, 20, 0, 20, 0};
        jPanel3Layout.rowHeights = new int[] {0, 20, 0, 20, 0, 20, 0, 20, 0, 20, 0, 20, 0, 20, 0};
        jPanel3.setLayout(jPanel3Layout);

        jLabel2.setText("ID:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.weighty = 0.1;
        jPanel3.add(jLabel2, gridBagConstraints);

        txtIdCaja.setEnabled(false);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.weightx = 0.1;
        gridBagConstraints.weighty = 0.1;
        jPanel3.add(txtIdCaja, gridBagConstraints);

        jLabel3.setText("Nombre de caja:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.weighty = 0.1;
        jPanel3.add(jLabel3, gridBagConstraints);

        txtNombre.setEnabled(false);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.ipadx = 154;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.weighty = 0.1;
        jPanel3.add(txtNombre, gridBagConstraints);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Saldos de moneda en caja"));
        jPanel1.setLayout(new java.awt.GridLayout(1, 4, 20, 20));

        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel6.setText("Bolivianos (Bs.):");
        jPanel1.add(jLabel6);

        txtSaldoBolivianos.setFocusLostBehavior(javax.swing.JFormattedTextField.COMMIT);
        txtSaldoBolivianos.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtSaldoBolivianosKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtSaldoBolivianosKeyReleased(evt);
            }
        });
        jPanel1.add(txtSaldoBolivianos);
        formatoTextoNumero();

        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel7.setText("Dolares ($):");
        jPanel1.add(jLabel7);

        txtSaldoDolares.setFocusLostBehavior(javax.swing.JFormattedTextField.COMMIT);
        jPanel1.add(txtSaldoDolares);
        formatoTextoNumero();

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.ipadx = 153;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.weighty = 0.1;
        jPanel3.add(jPanel1, gridBagConstraints);

        jLabel4.setText("Fecha Apertura:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 8;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.weighty = 0.1;
        jPanel3.add(jLabel4, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 8;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.ipadx = 101;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.weighty = 0.1;
        jPanel3.add(dateFechaVApertura, gridBagConstraints);

        jLabel8.setText("Fecha Cierre:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 10;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.weighty = 0.1;
        jPanel3.add(jLabel8, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 10;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.ipadx = 408;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.weighty = 0.1;
        jPanel3.add(dateFechaCierre, gridBagConstraints);

        rbtnEstado.setText("ACTIVO");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 12;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.weighty = 0.1;
        jPanel3.add(rbtnEstado, gridBagConstraints);

        jLabel1.setText("Estado de la Caja:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 12;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.weighty = 0.1;
        jPanel3.add(jLabel1, gridBagConstraints);

        getContentPane().add(jPanel3, java.awt.BorderLayout.CENTER);

        pInferior.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.RIGHT));

        btnDetalleCaja.setText("Detalle de Caja");
        btnDetalleCaja.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDetalleCajaActionPerformed(evt);
            }
        });
        pInferior.add(btnDetalleCaja);

        btnNuevo.setText("Nuevo");
        btnNuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNuevoActionPerformed(evt);
            }
        });
        pInferior.add(btnNuevo);

        btnGuardar.setText("Guardar");
        btnGuardar.setEnabled(false);
        btnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarActionPerformed(evt);
            }
        });
        pInferior.add(btnGuardar);

        btnEliminar.setText("Eliminar");
        btnEliminar.setEnabled(false);
        btnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarActionPerformed(evt);
            }
        });
        pInferior.add(btnEliminar);

        getContentPane().add(pInferior, java.awt.BorderLayout.PAGE_END);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void HabilitarBotones(boolean nue, boolean gua, boolean elim) {
        btnNuevo.setEnabled(nue);
        btnGuardar.setEnabled(gua);
        btnEliminar.setEnabled(elim);
    }
    private void formatoTextoNumero(){
        
        NumberFormat editFormat = NumberFormat.getNumberInstance(Locale.ENGLISH);
        // Para la edición, no queremos separadores de millares
        editFormat.setGroupingUsed(false);
        NumberFormatter enFormat = new NumberFormatter(editFormat);
        DefaultFormatterFactory currFactory = new DefaultFormatterFactory(enFormat);
        // El formateador de edición admite caracteres incorrectos
        enFormat.setAllowsInvalid(true);
        txtSaldoBolivianos.setFormatterFactory(currFactory);
        txtSaldoDolares.setFormatterFactory(currFactory);
    }
    private void habilitar(boolean estado){
            
        txtIdCaja.setEnabled(estado);
        txtNombre.setEnabled(estado);
        txtSaldoBolivianos.setEnabled(estado);
        txtSaldoDolares.setEnabled(estado);
        dateFechaVApertura.setEnabled(estado);
        dateFechaCierre.setEnabled(estado);
        rbtnEstado.setEnabled(estado);
    }
    private void limpiar(){
        
        txtIdCaja.setText("Null");
        txtNombre.setText("");
        txtSaldoBolivianos.setText("");
        txtSaldoDolares.setText("");
        
    }
    private void formInternalFrameOpened(javax.swing.event.InternalFrameEvent evt) {//GEN-FIRST:event_formInternalFrameOpened
        try {
            dtm = (DefaultTableModel) tblCaja.getModel();
            VerDatos();
            formatoTabla();
            modeloTabla.getModeloTabla(tblCaja, dtm);
            habilitar(false);
            HabilitarBotones(true, false, false);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(rootPane, e.toString());
        }
    }//GEN-LAST:event_formInternalFrameOpened

    private void tblCajaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblCajaMouseClicked
        // TODO add your handling code here:
        habilitar(true);
        txtIdCaja.setEditable(false);
        HabilitarBotones(true, true, true);
        int row = tblCaja.getSelectedRow();
        String estado = "";
        if (row != -1) {
            
            modif=true;
            idCaja = Integer.parseInt(dtm.getValueAt(row, 0).toString());
            txtIdCaja.setText((String)tblCaja.getValueAt(row, 0));
            txtNombre.setText((String) tblCaja.getValueAt(row, 1));
            txtSaldoBolivianos.setText((String) tblCaja.getValueAt(row, 2));
            txtSaldoDolares.setText((String) tblCaja.getValueAt(row, 3));
            dateFechaVApertura.setText((String) tblCaja.getValueAt(row, 4));
            dateFechaCierre.setText((String) tblCaja.getValueAt(row, 5));
            estado = (String)tblCaja.getValueAt(row, 6);
            if (estado.equals("1")) {
                rbtnEstado.setSelected(true);
            } else{
                rbtnEstado.setSelected(false);
            }
            
        }
        txtNombre.requestFocus();
    }//GEN-LAST:event_tblCajaMouseClicked

    private void btnNuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNuevoActionPerformed
        // TODO add your handling code here:
        habilitar(true);
        limpiar();
        HabilitarBotones(false, true, false);
        txtIdCaja.setEditable(false);  
        txtNombre.requestFocus();
        modif=false;
        idCaja = 0;
        
    }//GEN-LAST:event_btnNuevoActionPerformed

    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed
        // TODO add your handling code here:
        try {
            // Configuraion de las fechas en el txtfield
            int valor;
            java.sql.Timestamp fechaAP = new java.sql.Timestamp(dateFechaVApertura.getSelectedDate().getTimeInMillis());
            java.sql.Timestamp fechaCI = new java.sql.Timestamp(dateFechaCierre.getSelectedDate().getTimeInMillis());
            //recuperamos el estado del radiobutton
            if (rbtnEstado.isSelected()) {
                valor=1;
            } else {
                valor=0;
            }
            boolean gua = CRUD_Caja.Guardar(new Caja(idCaja, txtNombre.getText(), Double.parseDouble(txtSaldoBolivianos.getText()), 
                    Double.parseDouble(txtSaldoDolares.getText()), fechaAP,fechaCI, valor));
            if (gua) {
                if (modif) {
                    JOptionPane.showMessageDialog(rootPane, "Datos actualizados correctamente");
                    modif = false;
                } else {
                    JOptionPane.showMessageDialog(rootPane, "Datos guardados correctamente");
                }
                VerDatos();
                limpiar();
                habilitar(false);
                HabilitarBotones(true, false, false);
                
                idCaja=0;
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(rootPane, e.toString());
        }
    }//GEN-LAST:event_btnGuardarActionPerformed

    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed
        // TODO add your handling code here:
        try {
            Caja c = new Caja();
            c.setIdCaja(idCaja);
            
            boolean elim = CRUD_Caja.Eliminar(c);
            if (elim) {
                
                JOptionPane.showMessageDialog(rootPane, "Registro eliminado");
                
                VerDatos();
                limpiar();
                habilitar(false);
                HabilitarBotones(true, false, false);
                
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(rootPane, e.toString());
        }
    }//GEN-LAST:event_btnEliminarActionPerformed

    private void txtSaldoBolivianosKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtSaldoBolivianosKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSaldoBolivianosKeyPressed

    private void txtSaldoBolivianosKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtSaldoBolivianosKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSaldoBolivianosKeyReleased

    private void btnDetalleCajaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDetalleCajaActionPerformed
        // TODO add your handling code here:
        try {
            
            FormDetalleCaja formdetalleCaja = new FormDetalleCaja(Integer.parseInt(tblCaja.getValueAt(tblCaja.getSelectedRow(), 0).toString()));
            formdetalleCaja.setVisible(true);
            
        } catch (Exception e) {
            System.out.println("Error:"+e);
        }
        
    }//GEN-LAST:event_btnDetalleCajaActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDetalleCaja;
    private javax.swing.JButton btnEliminar;
    private javax.swing.JButton btnGuardar;
    private javax.swing.JButton btnNuevo;
    private datechooser.beans.DateChooserCombo dateFechaCierre;
    private datechooser.beans.DateChooserCombo dateFechaVApertura;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JPanel pInferior;
    private javax.swing.JPanel pInicio;
    private javax.swing.JRadioButton rbtnEstado;
    private javax.swing.JTable tblCaja;
    private javax.swing.JTextField txtIdCaja;
    private javax.swing.JTextField txtNombre;
    private javax.swing.JFormattedTextField txtSaldoBolivianos;
    private javax.swing.JFormattedTextField txtSaldoDolares;
    // End of variables declaration//GEN-END:variables

    public void VerDatos() throws ClassNotFoundException, SQLException {
        try {
            int nf = tblCaja.getRowCount();
            for (int i = 0; i < nf; i++) {
                dtm.removeRow(0);
            }
            for (Caja c : CRUD_Caja.ListaCajas()) {
                dtm.addRow(c.DatostoArray());
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(rootPane, e.toString());
        }
    }
    public void formatoTabla(){
        ModeloTabla.ocultarcolumna(0, tblCaja);
        ModeloTabla.formatoColumna(tblCaja, 1, 100, "text");
        ModeloTabla.formatoColumna(tblCaja, 2, 80, "numero");
        ModeloTabla.formatoColumna(tblCaja, 3, 80, "numero");
        ModeloTabla.formatoColumna(tblCaja, 4, 50, "text");
        ModeloTabla.formatoColumna(tblCaja, 5, 50, "text");
        ModeloTabla.formatoColumna(tblCaja, 6, 50, "text");
    }
}
