/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package sis_exchange;

import Controlador.CRUD_Caja;
import Controlador.CRUD_OperacionMoneda;
import Utilidades.CellRenderer;
import Utilidades.HeaderCellRenderer;
import java.sql.SQLException;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.JTableHeader;

/**
 *
 * @author EDWARD
 */
public class FormViewTransacciones extends javax.swing.JInternalFrame {

    public static DefaultTableModel dtm = null;

    /**
     * Creates new form FICursos
     */
    public FormViewTransacciones() {
        initComponents();
        dtm = (DefaultTableModel) tblTransacciones.getModel();
        getModeloTabla();
        try {
            VerDatos();
        } catch (Exception e) {
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        tblTransacciones = new javax.swing.JTable();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        setTitle("TRANSACCIONES DE CAJA");
        setToolTipText("");
        setPreferredSize(new java.awt.Dimension(777, 284));
        addInternalFrameListener(new javax.swing.event.InternalFrameListener() {
            public void internalFrameOpened(javax.swing.event.InternalFrameEvent evt) {
                formInternalFrameOpened(evt);
            }
            public void internalFrameClosing(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosed(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameIconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeiconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameActivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeactivated(javax.swing.event.InternalFrameEvent evt) {
            }
        });

        tblTransacciones.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "Nro", "HORA", "OPERACION", "MONEDA", "IMPORTE", "T / C", "SALDO"
            }
        ));
        jScrollPane2.setViewportView(tblTransacciones);

        getContentPane().add(jScrollPane2, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formInternalFrameOpened(javax.swing.event.InternalFrameEvent evt) {//GEN-FIRST:event_formInternalFrameOpened

    }//GEN-LAST:event_formInternalFrameOpened

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static javax.swing.JScrollPane jScrollPane2;
    private static javax.swing.JTable tblTransacciones;
    // End of variables declaration//GEN-END:variables

    public static void VerDatos() throws ClassNotFoundException, SQLException {
        int idCajaAct = 0;
        idCajaAct = FORM_PRINCIPAL.idcaja;
        try {
            int nf = tblTransacciones.getRowCount();
            for (int i = 0; i < nf; i++) {
                dtm.removeRow(0);
            }
            for (Object[] o : CRUD_OperacionMoneda.ListadeTransacciones(CRUD_Caja.getFechaApertura(idCajaAct), idCajaAct, Ingreso.idusuario)) {
                dtm.addRow(o);
            }
            tblTransacciones.setRowSelectionInterval(tblTransacciones.getRowCount() - 1, tblTransacciones.getRowCount() - 1);
            jScrollPane2.getVerticalScrollBar().setValue(jScrollPane2.getVerticalScrollBar().getMaximum());
        } catch (Exception e) {
            System.err.println("Erro" + e);
        }
    }

    public void getModeloTabla() {
        tblTransacciones.setModel(dtm);
        //color de los bordes de las celdas
        tblTransacciones.setGridColor(new java.awt.Color(214, 213, 208));
        //tamaño de columnas
        tblTransacciones.getColumnModel().getColumn(0).setPreferredWidth(10);
        tblTransacciones.getColumnModel().getColumn(1).setPreferredWidth(20);
        tblTransacciones.getColumnModel().getColumn(2).setPreferredWidth(30);
        tblTransacciones.getColumnModel().getColumn(3).setPreferredWidth(30);
        tblTransacciones.getColumnModel().getColumn(4).setPreferredWidth(20);
        tblTransacciones.getColumnModel().getColumn(5).setPreferredWidth(20);
        tblTransacciones.getColumnModel().getColumn(6).setPreferredWidth(20);
        //altura de filas
        tblTransacciones.setRowHeight(20);
        //se asigna el nuevo CellRenderer a cada columna segun su contenido
        tblTransacciones.getColumnModel().getColumn(0).setCellRenderer(new CellRenderer("text"));
        tblTransacciones.getColumnModel().getColumn(1).setCellRenderer(new CellRenderer("text center"));
        tblTransacciones.getColumnModel().getColumn(2).setCellRenderer(new CellRenderer("text center"));
        tblTransacciones.getColumnModel().getColumn(3).setCellRenderer(new CellRenderer("text"));
        tblTransacciones.getColumnModel().getColumn(4).setCellRenderer(new CellRenderer("numero"));
        tblTransacciones.getColumnModel().getColumn(5).setCellRenderer(new CellRenderer("numero"));
        tblTransacciones.getColumnModel().getColumn(6).setCellRenderer(new CellRenderer("numero"));
        //Se asigna nuevo header a la tabla
        JTableHeader jtableHeader = tblTransacciones.getTableHeader();
        jtableHeader.setDefaultRenderer(new HeaderCellRenderer());
        tblTransacciones.setTableHeader(jtableHeader);

    }
}
